version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - printenv
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run predeploy
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - COVERALLS_GIT_COMMIT=$CODEBUILD_SOURCE_VERSION node ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info