[[sources]]
  name = "global"
  database = "shapes"
  namespace = "public"  

  [[sources.layers]]
    minzoom   = 3
    name      = "water"
    table     = "water_gen3"
  [[sources.layers.variants]]
      minzoom = 4
      table   = "water_gen4"
  [[sources.layers.variants]]
      minzoom = 5
      table   = "water_gen5"
  [[sources.layers.variants]]
      minzoom = 6
      table   = "water_gen6"
  [[sources.layers.variants]]
      minzoom = 7
      table   = "simplified_water_polygons"
  [[sources.layers.variants]]
      minzoom = 8
      table   = "water_polygons"

  [[sources.layers]]
    minzoom   = 3
    name      = "bathymetry"
    table     = "bathymetry_gen3"
    keys      = ["depth"]
    postfix   = "ORDER BY depth"
  [[sources.layers.variants]]
      minzoom = 4
      table   = "bathymetry_gen4"
  [[sources.layers.variants]]
      minzoom = 5
      table   = "bathymetry"

  [[sources.layers]]
    minzoom   = 3
    name      = "lakes"
    table     = "lakes"
    keys      = ["name"]
    where     = ["minzoom <= !ZOOM!"]

  [[sources.layers]]
    minzoom   = 3
    name      = "rivers"
    table     = "rivers"
    keys      = ["name"]
    where     = ["minzoom <= !ZOOM!"]    

  [[sources.layers]]
    minzoom   = 3
    name      = "urban_areas"
    table     = "ne_10m_urban_areas"
    where     = ["min_zoom <= !ZOOM!"]

  [[sources.layers]]
    minzoom   = 3
    name      = "places"
    table     = "ne_10m_populated_places_simple"
    keys      = ["name", "featurecla as subclass"]
    where     = ["min_zoom <= !ZOOM!"]
    postfix   = "ORDER BY scalerank"

  [[sources.layers]]
    minzoom   = 3
    name      = "countries"
    table     = "label_countries"
    keys      = ["CASE WHEN area > 1000000 THEN name_en ELSE abbrev END as name"]
    where     = ["min_label <= !ZOOM! AND area > 500000"]
    postfix   = "ORDER BY scalerank"
    [[sources.layers.variants]]
      minzoom = 5
      keys    = ["CASE WHEN area > 500000 THEN name_en ELSE abbrev END as name"]
      where   = ["min_label <= !ZOOM! AND area > 100000"]
    [[sources.layers.variants]]
      minzoom = 6
      keys    = ["CASE WHEN area > 100000 THEN name_en ELSE abbrev END as name"]
      where   = ["min_label <= !ZOOM! AND area > 50000"]
    [[sources.layers.variants]]
      minzoom = 7
      keys    = ["CASE WHEN area > 50000 THEN name_en ELSE abbrev END as name"]
      where   = ["min_label <= !ZOOM! AND area > 10000"]
    [[sources.layers.variants]]
      minzoom = 8
      keys    = ["CASE WHEN area > 10000 THEN name_en ELSE abbrev END as name"]
      where   = ["min_label <= !ZOOM!"]

  [[sources.layers]]
    minzoom   = 3
    name      = "admin"
    table     = "ne_10m_admin_0_boundary_lines_land"
    geom_query = "ST_LineMerge(!GEOM!)"
    keys      = ["name", "featurecla as subclass", "type"]
    where     = ["min_zoom <= !ZOOM!"]
    postfix   = "ORDER BY scalerank"

[[sources]]
  name = "local"
  database = "local"
  namespace = "import"

  [[sources.layers]]
    name      = "landuse"
    minzoom   = 10
    table     = "landuse_gen10"
    keys      = ["subclass", "area", "name"]
    [[sources.layers.variants]]
      minzoom = 11
      table   = "landuse_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "landuse_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "landuse_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "landuse_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "landuse"

  [[sources.layers]]
    name      = "landcover"
    minzoom   = 8
    table     = "landcover_gen8"
    keys      = ["class", "subclass", "area", "surface", "name"]
    [[sources.layers.variants]]
      minzoom = 9
      table   = "landcover_gen9"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "landcover_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "landcover_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "landcover_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "landcover_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "landcover_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "landcover"

  [[sources.layers]]
    name       = "waterway"
    minzoom    = 8
    table      = "waterway_gen8"
    geom_query = "ST_LineMerge(ST_Collect(!GEOM!))"
    postfix    = "GROUP BY subclass, tunnel, layer, name"
    keys       = ["subclass", "tunnel", "layer", "name"]
    where      = ["subclass IN('river', 'canal')"]
    [[sources.layers.variants]]
      minzoom = 10
      table   = "waterway_gen10"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "waterway_gen12"
      where   = ["subclass IN('river', 'canal', 'stream')"]
    [[sources.layers.variants]]
      minzoom = 14
      table   = "waterway"
      keys    = ["subclass", "tunnel", "layer", "CASE WHEN (name_de <> '') IS NOT FALSE THEN name_de WHEN (name_en <> '') IS NOT FALSE THEN name_en ELSE name END as name"]      
      postfix = "GROUP BY subclass, tunnel, layer, name, name_de, name_en"
      where   = []
      
  [[sources.layers]]
    name      = "waterarea"
    minzoom   = 8
    table     = "waterarea_gen8"
    keys      = []
    [[sources.layers.variants]]
      minzoom = 9
      table   = "waterarea_gen9"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "waterarea_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "waterarea_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "waterarea_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "waterarea_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "waterarea_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "waterarea"

  [[sources.layers]]
    name      = "roads"
    minzoom   = 8
    table     = "roads_gen8"
    geom_query = "ST_LineMerge(ST_Collect(!GEOM!))"
    postfix = "GROUP BY class, subclass, oneway, tracktype, bridge, tunnel, service, layer, rank, bicycle, scale, sac, ref"
    keys      = [
      "class", 
      "subclass", 
      "oneway", 
      "tracktype", 
      "bridge", 
      "tunnel", 
      "service", 
      "CASE WHEN layer IS NULL THEN 0 ELSE layer END as layer", 
      "rank", 
      "bicycle", 
      "scale",
      "sac",
      "substring(ref from '\\w+') as ref_prefix", 
      "substring(ref from '\\d+') as ref_num", 
      "NULL as name"]
    [[sources.layers.variants]]
      minzoom = 10
      table   = "roads_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "roads_gen11"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "roads_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "roads_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "roads_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      buffer = 128
      table   = "roads_gen15"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "roads"
      buffer = 256
      keys      = [
        "class", 
        "subclass", 
        "oneway", 
        "tracktype", 
        "bridge", 
        "tunnel", 
        "service", 
        "CASE WHEN layer IS NULL THEN 0 ELSE layer END as layer", 
        "rank", 
        "bicycle", 
        "scale",
        "sac",  
        "substring(ref from '\\w+') as ref_prefix", 
        "substring(ref from '\\d+') as ref_num", 
        "name"]
    postfix = "GROUP BY class, subclass, oneway, tracktype, bridge, tunnel, service, layer, rank, bicycle, scale, sac, ref, name ORDER BY rank DESC"

  [[sources.layers]]
    minzoom   = 11
    name      = "cycleroute"
    sql       = "SELECT ref, name, ST_AsMvtGeom(ST_LineMerge(ST_Collect(geometry)), !BBOX!) AS geom from import.cycleroute where (geometry && !BBOX!) AND ST_GeometryType(geometry)='ST_LineString' group by ref, name order by ref desc NULLS last, name desc NULLS last"

  [[sources.layers]]
    minzoom    = 9
    name       = "railway"
    table      = "railway"
    geom_query = "ST_LineMerge(ST_Collect(!GEOM!))"
    keys       = ["class", "subclass", "zorder", "bridge", "tunnel", "service"]
    where      = ["subclass NOT IN('subway', 'tram')", "(attraction <> '') IS NOT TRUE", "(service <> '') IS NOT TRUE"]
    postfix    = "GROUP BY class, subclass, zorder, bridge, tunnel, service"
    [[sources.layers.variants]]
      minzoom   = 15
      where     = ["(attraction <> '') IS NOT TRUE"]

  [[sources.layers]]
    minzoom   = 10
    name      = "transportation"
    table     = "transportation"
    keys      = ["class", "subclass", "CASE WHEN (name_de <> '') IS NOT FALSE THEN name_de WHEN (name_en <> '') IS NOT FALSE THEN name_en ELSE name END as name"]
    where     = ["NOT ST_IsClosed(geometry)"]


  [[sources.layers]]
    minzoom   = 10
    name      = "manmade"
    sql       = "select ST_AsMvtGeom(geometry, !BBOX!, 4096, 64) as geom, class, subclass, ST_Length(geometry)::integer as length, ST_IsClosed(geometry) as polygon from import.manmade_lines_gen13 WHERE (geometry && !BBOX!)"
    [[sources.layers.variants]]
      minzoom = 14
      sql       = """select ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, ST_Length(geometry)::integer as length, ST_IsClosed(geometry) as polygon from import.manmade_lines WHERE (geometry && !BBOX!) 
                  UNION ALL
                  select ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, ST_Perimeter(geometry)::integer as length, TRUE as polygon from import.manmade_polygons WHERE (geometry && !BBOX!) 
                  UNION ALL
                  select ST_AsMvtGeom(geometry, !BBOX!) as geom, class, subclass, 0 as length, FALSE as polygon from import.manmade_points WHERE (geometry && !BBOX!)
                  """

  [[sources.layers]]
    minzoom   = 14
    name      = "piste"
    table     = "piste"
    keys      = ["difficulty"]
    where     = ["NOT ST_IsClosed(geometry)"]

  [[sources.layers]]
    minzoom   = 10
    name      = "admin"
    table     = "admin"
    keys      = ["ref", "level"]
    where     = ["level = 2"]

  [[sources.layers]]
    minzoom   = 13
    maxzoom   = 15
    name      = "buildings-large"
    table     = "buildings_gen14"
    keys      = []
    where     = ["ST_Area(geometry)>10000"]

  [[sources.layers]]
    minzoom   = 14
    name      = "buildings"
    table     = "buildings_gen14"
    keys      = []
    [[sources.layers.variants]]
      minzoom = 15
      table   = "buildings"

  [[sources.layers]]
    minzoom   = 18
    name      = "housenumbers"
    table     = "housenumbers"
    keys      = ["number", "name"]

  [[sources.layers]]
    name      = "waterlabels"
    minzoom   = 8
    table     = "label_waterarea_gen8"
    keys      = ["subclass", "area", "ele", "name"]
    [[sources.layers.variants]]
      minzoom = 10
      table   = "label_waterarea_gen10"
    [[sources.layers.variants]]
      minzoom = 12
      table   = "label_waterarea_gen12"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "label_waterarea_gen14"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "label_waterarea"

  [[sources.layers]]
    minzoom   = 8
    name      = "label"
    table     = "label_gen8"
    prefix    = "DISTINCT ON(pop, name)"
    keys      = ["class", "subclass", "name", "ele", "pop"]
    postfix   = "ORDER BY pop DESC NULLS LAST, name"
    [[sources.layers.variants]]
      minzoom = 10
      table   = "label_gen10"
    [[sources.layers.variants]]
      minzoom = 11
      table   = "label_gen11"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "label_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "label_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "label_gen15"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "label"

  [[sources.layers]]
    minzoom   = 11
    name      = "poi"
    table     = "poi_cluster_gen11"
    keys      = ["count", "class", "subclass", "name", "ele", "access", "subway", "religion", "parking"]
    [[sources.layers.variants]]
      minzoom = 12
      table   = "poi_cluster_gen12"
    [[sources.layers.variants]]
      minzoom = 13
      table   = "poi_cluster_gen13"
    [[sources.layers.variants]]
      minzoom = 14
      table   = "poi_cluster_gen14"
    [[sources.layers.variants]]
      minzoom = 15
      table   = "poi_cluster_gen15"
    [[sources.layers.variants]]
      minzoom = 16
      table   = "poi_cluster_gen16"
    [[sources.layers.variants]]
      minzoom = 17
      table   = "poi_cluster_gen17"
    [[sources.layers.variants]]
      minzoom = 18
      table   = "poi"
      keys    = ["1 as count", "class", "subclass", "name", "ele", "access", "subway", "religion", "parking"]
